CAMERA_FPS_LIMIT = 30
FRONT_CAMERA_WIDTH = 640
FRONT_CAMERA_HEIGHT = 360
PROFILE_CAMERA_WIDTH = 360
PROFILE_CAMERA_HEIGHT = 640

POSE_RIGHT_SHOULDER = 12
POSE_LEFT_SHOULDER = 11
POSE_RIGHT_ELBOW = 14
POSE_LEFT_ELBOW = 13
POSE_RIGHT_WRIST = 16
POSE_LEFT_WRIST = 15
POSE_RIGHT_HIP = 24
POSE_LEFT_HIP = 23

FRONT_FLEX_THRESHOLD = 30
FRONT_EXTEND_THRESHOLD = 140
PROFILE_FLEX_THRESHOLD = 80
PROFILE_EXTEND_THRESHOLD = 130
PHASE_STABILITY_FRAMES = 5
FRONT_ANGLE_SMOOTHING = 0.9
FRONT_ELBOW_DIST_SMOOTHING = 0.5
FRONT_TRUNK_SMOOTHING = 0.5
PROFILE_ANGLE_SMOOTHING = 0.9
PROFILE_TRUNK_SMOOTHING = 0.5

FRONT_WRIST_TO_SHOULDER_FLEX_THRESHOLD = 0.25
PROFILE_WRIST_TO_SHOULDER_FLEX_THRESHOLD = 0.25
FRONT_WRIST_DIST_SMOOTHING = 0.7
PROFILE_WRIST_DIST_SMOOTHING = 0.7

VERTICAL_STANCE_THRESHOLD = 20