from dotenv import load_dotenv
from os import getenv

load_dotenv()


# ===============
# CAMERA SETTINGS
# ===============

CAMERA_FPS_LIMIT = 30   # The minimum fps for front and profile cameras
FRONT_CAMERA_WIDTH = 640
FRONT_CAMERA_HEIGHT = 360
PROFILE_CAMERA_WIDTH = 360
PROFILE_CAMERA_HEIGHT = 640

PROFILE_CAMERA_IP = getenv('PROFILE_CAMERA_IP')
PROFILE_CAMERA_PORT = getenv('PROFILE_CAMERA_PORT')
PROFILE_CAMERA_URL = f'http://{PROFILE_CAMERA_IP}:{PROFILE_CAMERA_PORT}/video'

POSE_RIGHT_SHOULDER = 12
POSE_LEFT_SHOULDER = 11
POSE_RIGHT_ELBOW = 14
POSE_LEFT_ELBOW = 13
POSE_RIGHT_WRIST = 16
POSE_LEFT_WRIST = 15
POSE_RIGHT_HIP = 24
POSE_LEFT_HIP = 23

# ===============
# ANGLE THRESHOLDS
# ===============

FRONT_FLEX_THRESHOLD = 30
FRONT_EXTEND_THRESHOLD = 140
PROFILE_FLEX_THRESHOLD = 80
PROFILE_EXTEND_THRESHOLD = 130
PHASE_STABILITY_FRAMES = 7
FRONT_ANGLE_SMOOTHING = 0.9
FRONT_ELBOW_DIST_SMOOTHING = 0.5
FRONT_TRUNK_SMOOTHING = 0.5
PROFILE_ANGLE_SMOOTHING = 0.9
PROFILE_TRUNK_SMOOTHING = 0.5