FRONT_FLEX_THRESHOLD = 30
FRONT_EXTEND_THRESHOLD = 140
PROFILE_FLEX_THRESHOLD = 80
PROFILE_EXTEND_THRESHOLD = 130

PHASE_STABILITY_FRAMES = 5

FRONT_ANGLE_SMOOTHING = 0.9
FRONT_ELBOW_DIST_SMOOTHING = 0.5
PROFILE_ANGLE_SMOOTHING = 0.9
PROFILE_TRUNK_SMOOTHING = 0.5

FRONT_WRIST_DIST_SMOOTHING = 0.7
PROFILE_WRIST_DIST_SMOOTHING = 0.7

VERTICAL_STANCE_THRESHOLD = 20
TRUNK_ANGLE_THRESHOLD = 10