FRONT_FLEX_THRESHOLD = 90
FRONT_EXTEND_THRESHOLD = 160
PROFILE_FLEX_THRESHOLD = 90
PROFILE_EXTEND_THRESHOLD = 160

STABILITY_FRAMES = 3

FRONT_ANGLE_SMOOTHING = 0.9
PROFILE_ANGLE_SMOOTHING = 0.9
PROFILE_TRUNK_SMOOTHING = 0.5

ARM_SYNC_THRESHOLD = 20
TRUNK_ANGLE_THRESHOLD = 15
ELBOW_FORWARD_MIN = 30

ACTIVE_ZONE_WRIST_Y_MAX = 0.5
ACTIVE_ZONE_WRIST_Y_MIN = 0.1

SHOULDER_Y_OFFSET = 0.05

REP_COUNT_AT_TOP = False

REQUIRE_START_POSITION = True
START_POSITION_MIN_ANGLE = 70
START_POSITION_MAX_ANGLE = 110