CAMERA_FPS_LIMIT = 30
FRONT_CAMERA_WIDTH = 640
FRONT_CAMERA_HEIGHT = 360
PROFILE_CAMERA_WIDTH = 360
PROFILE_CAMERA_HEIGHT = 640

# MediaPipe pose landmark indices
POSE_NOSE = 0
POSE_RIGHT_SHOULDER = 12
POSE_LEFT_SHOULDER = 11
POSE_RIGHT_ELBOW = 14
POSE_LEFT_ELBOW = 13
POSE_RIGHT_WRIST = 16
POSE_LEFT_WRIST = 15
POSE_RIGHT_HIP = 24
POSE_LEFT_HIP = 23